# -*- coding: utf-8 -*-
"""Messi vs Ronaldo - An Analytical Debate

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15U3O_3_GmMMQC-yKw5r7V0q4mwQQMkOY

## Flow of the Project:
1. Get data from [Understat](https://understat.com/) for Messi and Ronaldo
3. Data Cleaning and Exploration of the data for Messi and Ronaldo on different aspects
2. Comparative Analysis
3. Shot Analysis
3. The Final comparison
"""

import json
import pandas as pd
from bs4 import BeautifulSoup
from urllib.request import urlopen
